name: docker

on:
  push:
    branches-ignore: [gh-pages]
    tags:
    - v*
env:
  IMAGE_NAME: dirindex
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    - name: setup docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: login ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        context: docker
        file: docker/Dockerfile
        build-args:
          tag: ${{ github.ref_name }}
        tags:
        - ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        - ghcr.io/${{ github.repository }}:latest
